version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:${POSTGRESDB_PORT}"
    environment:
      POSTGRES_DB: "${POSTGRESDB_NAME}"
      POSTGRES_USER: "${POSTGRESDB_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRESDB_PASSWORD}"
  app:
    build: .
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: "${POSTGRESDB_URL}:${POSTGRESDB_PORT}/${POSTGRESDB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRESDB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRESDB_PASSWORD}"
    depends_on:
      - db
